[package]
name = "msnnext"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
name = "msnnext_core"

[dependencies]
blake3 = "1"
base64 = "0.22"
chacha20poly1305 = "0.10"
cbor4ii = { version = "0.3", features = ["serde1", "use_std"] }
futures = "0.3"
imagesize = "0.14"
libp2p = { version = "0.56", features = ["autonat", "cbor", "dcutr", "identify", "kad", "macros", "mdns", "noise", "ping", "quic", "relay", "request-response", "tcp", "tokio", "yamux"] }
msnnext-protocol = { path = "../../crates/protocol" }
notify-rust = "4"
rusqlite = { version = "0.37", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["io-std", "io-util", "macros", "rt-multi-thread"] }
qrcode = { version = "0.14.1", default-features = false }
aws-lc-rs = { version = "1.17.1", default-features = false, features = ["aws-lc-sys", "prebuilt-nasm"] }
zeroize = { version = "1.9.0", features = ["zeroize_derive"] }
